### ISSUE TITLE
Can't get user access token

### ISSUE THREAD

**Issue by mortocks** [vhpoet/facebook-cli#3]
assume I'm doing something wrong but can't workout how to get a user access token. I'm making a request with 

```
curl https://graph.facebook.com/oauth/access_token?client_id=MYAPPID&client_secret=MYAPPSECRET&grant_type=client_credentials 
```

and using that as the access token but then requests are getting oauth errors. Might also have my FB app setup incorrectly.

**Comment by vhpoet** [comment]
@mortocks [here's the url](https://github.com/vhpoet/facebook-cli/blob/daa51715708ee968e5a6cb874981fba9e1dc5f22/auth.js#L26-L30) for getting an access token
